### ISSUE TITLE
Updating the ucrReceiver to allow for rearranging items in the receiver

### ISSUE THREAD

**Issue by lilyclements** [IDEMSInternational/R-Instat#6506]
At the moment the receiver takes variables from the selector. For the summary tables dialogs, we want to have some up/down arrows to allow for the receiver to additionally rearrange variables. This would be similar to the control to move around factor levels, or layers in the geom function.

![image](https://user-images.githubusercontent.com/21180424/120235936-095b8900-c253-11eb-8f10-d4917c686aa1.png)

Because we want this for the summary table dialogs, we would have a ucrNud to determine how many columns there are (sorted in the summary dialog code). So it would be useful to have a line that indicates where a split between columns and rows are

![image](https://user-images.githubusercontent.com/21180424/120235953-10829700-c253-11eb-8da5-a5b2f27addd1.png)

_Side note: In the dialog code we will sort taking the variables above the line to set as columns, and same to set as rows.
We just need a way to distinguish/say "for items above the line"_

**Comment by rdstern** [comment]
@lilyclements I am happy for the multiple receiver to become more flexible and like the idea.  But I also heard that David thinks this is the ideal task for Chris Marsh to start working on as he joins us.

I am slightly confused why that should be? As you know I am very keen on the tables working well.  But there will also be a NUD to say how many variables are column, and currently all you have to do is be a bit careful in the order of choosing the variables from the data selector.  

So is the reason because you would like to encourage users to try different layouts easily?

**Comment by lilyclements** [comment]
As well as encouraging different layouts, this also allows for some flexibility to easily reorder their rows and columns (especially if the last variable they put it they actually want to be the first variable).
Also having this "line" in the receiver adds some clarity as to which variables will be in the columns and which in the rows.
