### ISSUE TITLE
Another very small change in the front screen

### ISSUE THREAD

**Issue by rdstern** [IDEMSInternational/R-Instat#9079]
@Fidel365 I have just noticed the inconsistency here!

![image](https://github.com/user-attachments/assets/788a738e-4de4-4190-8528-dc42ef950863)

Could you please swap the top 2 items in the introductory screen, so they match the order of the 3 options in the File menu.  Sorry - I should have noticed before!

Thanks

**Comment by rachelkg** [comment]
Hello @Fidel365

On my review of the front screen I notice that the 'Paste data from clipboard...' is not properly capitalised.  Please could you make it 'Paste Data from Clipboard...' so that it matches the other items.
![2024-07-25_15-07-45](https://github.com/user-attachments/assets/93e85750-8199-4edc-a10a-60c19f93b2a9)

Thanks, 

Rachel

**Comment by rdstern** [comment]
@Fidel365 @N-thony I am happy!  And closing.
