### ISSUE TITLE
Making tabs active only for selected summaries in the export to google buckets dialog

### ISSUE THREAD

**Issue by jkmusyoka** [IDEMSInternational/R-Instat#9100]
@Vitalis95
I would like to suggest another improvement on the export to google buckets dialogue, if possible before the end of this week so that these changes can be available for our Zambia and Malawi trainings from next week. 
Is it possible to have the tabs in the upload summaries sub-dialog active only for checkboxes that have been ticked in the summaries section in the main dialogue? i.e. if a summary is not selected in the main dialogue for uploading then its tab in the subsequent sub-dialog should be "frozen".

**Comment by rdstern** [comment]
@jkmusyoka I have no problem with the tabs being disabled.  However the main point is that when Ok is pressed it only processes the component where the checkbox is clicked.
For example I could always check (say) temperatures.  This will enable the temperature tab.  Now I half-complete it.  Then I decide I won't do temperatures.  I just do rainfall and then press Ok.  I would like that to not give an error, because it ignores the temperaure options, because the option wasn't ticked when Ok is pressed.

If you agree, then it is not particularly important whether the tabs are enabled or not.

**Comment by jkmusyoka** [comment]
@rdstern I agree. Over to you @Vitalis95

**Comment by Vitalis95** [comment]
@N-thony , this issue is complete, I am closing it.
