### ISSUE TITLE
Error in the sort dialog

### ISSUE THREAD

**Issue by berylwaswa** [IDEMSInternational/R-Instat#9269]
**Describe the bug**
When I use the sort dialog with the descending option it gives me an error, but with the ascending option it works fine.

**To Reproduce**
1. I imported the dinosaurs list from the new data frame dialog.
2. I then used Prepare > Column: Text> Transform> Length to get a column for the lengths of the dinosaur names
3. Then I copied the row numbers into a column called row
4. Right-click in the length column and choose Sort then change the option to descending and click ok.

**Expected behaviour**
I expected it to rearrange the values so that I could see the longest name but instead I got the error below.

**Screenshots**
![din](https://github.com/user-attachments/assets/e4cec472-c3c7-475d-aa93-989e16a499fb)

**R script or commands**

data_book$sort_dataframe(data_name="dinosaurs", col_names="length", decreasing=TRUE)

**Additional context**
When I press Ok with the ascending order selected there's no error.

**Comment by rdstern** [comment]
@berylwaswa could you check in the merged version.  It was also reported in #9255 and I hope is now fixed>

**Comment by rdstern** [comment]
@berylwaswa we knew that.

So instead of telling us what you did, we were asking you to check in thye merged version.  So you become a tester that things get fixed, as well as a reporter of errors.  If you found it was fixed, then you close this issue.  This time, as I think it is fixed, I am closing the issue for you.
